version: '3'
services:

  redis:
    image: redis

  mongodb:
    image: mongo
    volumes:
      - /tmp/mongo:/data/db

  mosca:
    image: eclipse-mosquitto
    volumes:
      - /tmp/mosca:/db
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf

  publisher:
    build: publisher
    depends_on:
      - "mosca"
      - "subscriber"

  subscriber:
    build: subscriber
    depends_on:
      - "redis"
      - "mongodb"
      - "mosca"

